masterdata manage translations
lensbysits/core-backend pull request #69
Opened 2023-04-27 18:31 UTC by dageorgero

2023-05-09 19:13 UTC, meghuizen approved these changes

2023-05-12 06:48 UTC, Johanh-od requested changes

2023-05-12 06:48 UTC, Johanh-od commented on Core/Data.EF/ApplicationDbContext.cs
> +        InitializeTranslation();
Do we really want this in the ApplicationDbContext and forcing every context to use this? @jstorteboom

2023-05-12 06:51 UTC, Johanh-od commented
Can we add a short readme how you initialize and configure the translations?

2023-05-12 07:00 UTC, Johanh-od commented on Services/Masterdata/Services.Masterdata/Helpers/LanguageHelper.cs
> +public static class LanguageHelper
Lets rephrase this to LanguageConfiguration and move it to a Core lib, so multi language support is available from the core and not masterdata specific

2023-05-12 07:00 UTC, Johanh-od commented on Services/Masterdata/Services.Masterdata/Repositories/IMasterdataRepository.cs
>  public interface IMasterdataRepository
Tip: you better split this repo **in the future**, so it has only 1 responsibility instead of 2 (masterdata type & master data item logic)

2023-05-12 07:00 UTC, Johanh-od commented on Services/Masterdata/Services.Masterdata/Repositories/IMasterdataRepository.cs
>  public interface IMasterdataRepository
It also reduces the lines of code in 1 file if the class has only 1 responsibility

2023-05-12 07:00 UTC, Johanh-od commented on Services/Masterdata/Services.Masterdata/Repositories/IMasterdataRepository.cs
>  public interface IMasterdataRepository
It also prevents the use of the (ugly) region statements in your file :)

2023-05-12 13:07 UTC, merged

2023-05-12 14:31 UTC, dageorgero commented on Services/Masterdata/Services.Masterdata/Helpers/LanguageHelper.cs
> +public static class LanguageHelper
i want to keep it on a masterdata level for now. the translation is functional for now on a masterdata level. we can move this language configuration file in a future story, when the translation will be fully developed for on a framework level!

2023-05-12 14:33 UTC, dageorgero commented
> Can we add a short readme how you initialize and configure the translations?
I think for now it should be used/tested on masterdata. It needs some fine tuning to be more developer friendly for using in other apps.